/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FeedRouteImport } from './routes/feed/route'
import { Route as IndexImport } from './routes/index'
import { Route as FeedIndexImport } from './routes/feed/index'
import { Route as FeedIdImport } from './routes/feed/$id'

// Create/Update Routes

const FeedRouteRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FeedIndexRoute = FeedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedRouteRoute,
} as any)

const FeedIdRoute = FeedIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FeedRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRoute
    }
    '/feed/$id': {
      id: '/feed/$id'
      path: '/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof FeedIdImport
      parentRoute: typeof FeedRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexImport
      parentRoute: typeof FeedRouteImport
    }
  }
}

// Create and export the route tree

interface FeedRouteRouteChildren {
  FeedIdRoute: typeof FeedIdRoute
  FeedIndexRoute: typeof FeedIndexRoute
}

const FeedRouteRouteChildren: FeedRouteRouteChildren = {
  FeedIdRoute: FeedIdRoute,
  FeedIndexRoute: FeedIndexRoute,
}

const FeedRouteRouteWithChildren = FeedRouteRoute._addFileChildren(
  FeedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRouteRouteWithChildren
  '/feed/$id': typeof FeedIdRoute
  '/feed/': typeof FeedIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed/$id': typeof FeedIdRoute
  '/feed': typeof FeedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/feed': typeof FeedRouteRouteWithChildren
  '/feed/$id': typeof FeedIdRoute
  '/feed/': typeof FeedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feed' | '/feed/$id' | '/feed/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feed/$id' | '/feed'
  id: '__root__' | '/' | '/feed' | '/feed/$id' | '/feed/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRouteRoute: typeof FeedRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRouteRoute: FeedRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/feed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/feed": {
      "filePath": "feed/route.tsx",
      "children": [
        "/feed/$id",
        "/feed/"
      ]
    },
    "/feed/$id": {
      "filePath": "feed/$id.tsx",
      "parent": "/feed"
    },
    "/feed/": {
      "filePath": "feed/index.tsx",
      "parent": "/feed"
    }
  }
}
ROUTE_MANIFEST_END */
